# Libre Testnet P2P Peers
# Format: provider|address|region
CryptoBloks|p2p.testnet.libre.iad.cryptobloks.io:9876|US-East
CryptoBloks|p2p.testnet.libre.pdx.cryptobloks.io:9876|US-West
Amsterdam|libretest.eu.eosamsterdam.net:9911|EU-Germany
EOSphere|peer1-libre-testnet.eosphere.io:9876|AU-Perth
eosusa|test.libre.p2p.eosusa.io:19885|US-East
