# Libre Mainnet P2P Peers
# Format: provider|address|region
Amsterdam|libre.eu.eosamsterdam.net:9180|EU-Finland
CryptoBloks|p2p.libre.iad.cryptobloks.io:9876|US-East
CryptoBloks|p2p.libre.pdx.cryptobloks.io:9876|US-East
eosphere|peer1-libre.eosphere.io:9876|AU-Perth
eosusa|libre.p2p.eosusa.io:9885|US-East
genereos|peer1.libre.genereos.io:9876|EU-London
librenodeone|peer-libre.nodeone.network:9872|EU-Germany
libretech|seed.libre.org:9876|US-East
rioblocks|p2p.libre.rioblocks.io:8152|SA-Brazil
sweden|p2p.libre.eossweden.org:9976|EU-Germany